Gizmo docs
BabylonJS/OldDocumentationSite pull request #1088
Opened 2018-06-22 00:23 UTC by TrevorDev

https://github.com/BabylonJS/Babylon.js/issues/4141
https://github.com/BabylonJS/Documentation/issues/826
https://github.com/BabylonJS/Documentation/issues/1022

2018-06-22 03:03 UTC, deltakosh requested changes
Generally speaking we need that all properties and methods are mentioned here

2018-06-22 03:03 UTC, deltakosh commented on content/How_To/mesh/UtilityLayerRenderer.md
> +
These behaviors must be referenced in the global behavior page

2018-06-22 03:03 UTC, deltakosh commented on content/How_To/mesh/Gizmo.md
> +var gizmo = new BABYLON.AxisDragGizmo(utilLayer, new BABYLON.Vector3(1,0,0), BABYLON.Color3.FromHexString("#00b894"));
Can we invert the parameters and create a default utility layer if none is provided
The default utility layer should be shared between gizmos when no utility layer is defined

2018-06-22 03:03 UTC, deltakosh commented on content/How_To/mesh/Gizmo.md
> + - [Single Axis Position](https://www.babylonjs-playground.com/#31M2AP#3)
The API should also be mentioned here for search indexation purpose

2018-06-22 03:03 UTC, deltakosh commented on content/How_To/mesh/Gizmo.md
> + - [Multi Axis Position](https://www.babylonjs-playground.com/#31M2AP#6)
Same here

2018-06-26 00:59 UTC, TrevorDev commented on content/How_To/mesh/Gizmo.md
> + - [PositionGizmo](https://www.babylonjs-playground.com/#31M2AP#6)
All these playground need to be updated. Waiting for https://github.com/BabylonJS/Babylon.js/pull/4606

2018-06-26 17:07 UTC, deltakosh commented on content/How_To/mesh/Gizmo.md
> + - [PositionGizmo](https://www.babylonjs-playground.com/#31M2AP#6)
merged and published

2018-06-27 20:01 UTC, deltakosh approved these changes

2018-06-27 20:01 UTC, deltakosh commented
Perfect.. Please socialize it with the community :)

2018-06-27 20:01 UTC, merged