Combine Babylon.js and Pixi.js
BabylonJS/OldDocumentationSite pull request #1259
Opened 2018-09-23 15:17 UTC by quocsinh

2018-09-24 13:14 UTC, deltakosh commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +Pixi.js has full webgl support, a best framework for 2D game and app with rendering speed very fast. Would be great if you want make UI game with Pixi.js and combine with Babylon.js. This is a perfec
We should not mention "best" here as other 2d  frameworks are also great:)

2018-09-24 13:15 UTC, deltakosh reviewed
You need to add a reference to this file in the data file.

2018-09-24 13:15 UTC, deltakosh commented
Adding @BabylonJSGuide for review

2018-09-24 14:22 UTC, quocsinh commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +Pixi.js has full webgl support, a best framework for 2D game and app with rendering speed very fast. Would be great if you want make UI game with Pixi.js and combine with Babylon.js. This is a perfec
You are right, i'm too negligent :) . What words should we use? "a great framework... "??

2018-09-24 17:21 UTC, deltakosh commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +Pixi.js has full webgl support, a best framework for 2D game and app with rendering speed very fast. Would be great if you want make UI game with Pixi.js and combine with Babylon.js. This is a perfec
No need to apologize :)
Yes great framework is fine!

2018-09-25 13:55 UTC, quocsinh commented
DONE :)

2018-10-01 17:32 UTC, BabylonJSGuide commented
@quocsinh my apologies for not reviewing your PR earlier. I will be able to do so over the next couple of days. What a great idea and I hope you don't mind me putting the text into a more native English style. I had a go at the fiddle and by using scene.autoClear = false was able to put a pixi stage behind and in front of the sphere https://jsfiddle.net/y5q7Lb1v/41/. It would be really good if you could produce a much better fiddle perhaps using different images. How about a Pixi animated background. I do not know enough about Pixi to do so. Will start my review tomorrow and thank you for your contribution.

2018-10-02 07:39 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
It is unusual to name the author in the documentation and would prefer that you deleted it.

2018-10-02 07:44 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest:
[Pixi.js](http://www.pixijs.com/) is a fast, lightweight, open source 2D library with full support for webGL with a very fast rendering speed. It is great to use as a UI in combination with Babylon.js, making a perfect duo for your web game world.

2018-10-02 07:50 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
This is more stating **why** to use Pixi.js rather than **when** you should use it with Babylon.js and repeats what is in the opening paragraph. Can you give more times **when** it would be good with Babylon.js. For example could it be used as an animated UI?

2018-10-02 07:52 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest:

The *clearBeforeRender* and *autoStart* are two very important properties that must be used and set to *false* *false*.

2018-10-02 07:59 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggets:

* [Working JSFiddle Example Pixi.js in Front](https://jsfiddle.net/y5q7Lb1v/40/)

2018-10-02 08:16 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest

## WebGL1 Problems

2018-10-02 08:23 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest

When your browser is running webGL1 then you need to reset the Pixi.js context first for each rendering as below.

```
engine.runRenderLoop(function() { 
    if(engine.webGLVersion === 1) {
        pixiRenderer.reset();
    }
    scene.render();    	
    engine.wipeCaches(true);
  
    pixiRenderer.reset();
    pixiRenderer.render(stage);
});
```

2018-10-02 08:24 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest:

Pixi.js Versions

2018-10-02 08:32 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +* Don't use Pixi.js v5 alpha, them still a few errors. I will update the doc when Pixi.js v5 released.
Suggest:

Always use the [latest released version of Pixi.js](https://github.com/pixijs/pixi.js/releases)

2018-10-02 08:34 UTC, BabylonJSGuide requested changes
Please make changes in line with those requested

2018-10-02 13:04 UTC, BabylonJSGuide commented
Mixing Pixi.js and Babylon.js is such a good idea I have been playing. Have added this https://jsfiddle.net/y5q7Lb1v/42/ as the behind and in front example

2018-10-03 13:23 UTC, quocsinh commented
Thank JohnK for your reviews and suggestion! I will make changes it.

2018-10-10 14:18 UTC, quocsinh commented
Sorry for the late update, i'm very busy during this time. 
@BabylonJSGuide If there are other problems, please help me finish it. Thank you!

2018-10-10 15:00 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest that this line


The above example working great when your browser support WebGL2 but will have a bit of issues when run on WebGL1.

is no longer needed and can be deleted

2018-10-10 15:01 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest that the following line is not needed as covered in example

2018-10-10 15:05 UTC, BabylonJSGuide commented on content/resources/Library/BabylonJS_and_PixiJS.md
> +
Suggest either delete this section or replace with reasons to state **when** it would be good to use with Babylon.js

2018-10-10 15:11 UTC, BabylonJSGuide commented
Thank you for the changes you have made. In a couple of sections I may not have been clear enough in my suggestions so have, hopefully, re-stated them more clearly. It is very close to being accepted. When you have time please check them out. If there are reasons that you prefer them not to be changed please let me know.

2018-10-15 13:06 UTC, BabylonJSGuide commented
As the author has not objected to the changes and I think the PR should go ahead I will approve it as is and commit changes myself once merged.

2018-10-15 13:06 UTC, BabylonJSGuide approved these changes

2018-10-15 13:28 UTC, deltakosh commented
OK thanks a lot

2018-10-15 13:29 UTC, merged