Update from http to https where appropriate
BabylonJS/OldDocumentationSite pull request #1315
Opened 2018-11-09 16:43 UTC by BabylonJSGuide

2018-11-09 18:51 UTC, deltakosh requested changes

2018-11-09 18:51 UTC, deltakosh commented on README.md
> +    * [Babylon 101](https://www.babylonjs.com/babylon101)
This  should stay as doc  no?

2018-11-10 09:45 UTC, BabylonJSGuide commented on README.md
> +    * [Babylon 101](https://www.babylonjs.com/babylon101)
These are not the only doc links that I wrongly changed. Am closing this PR as it contains errors.

2018-11-10 09:45 UTC, BabylonJSGuide commented
Closing because of errors

2018-11-10 09:45 UTC, closed without merging