Add how to disappear default controller mesh
BabylonJS/OldDocumentationSite pull request #1597
Opened 2019-07-04 18:36 UTC by flushpot1125

Only using attachToMesh() function remains native controller meshes. The option of "controllerMeshes:false" can be disappeared the native meshes.

See controllerMeshes option of the link.   
https://doc.babylonjs.com/api/interfaces/babylon.vrexperiencehelperoptions

2019-07-04 18:39 UTC, deltakosh commented on content/How_To/camera/WebVR_Camera.md
> +The default controller mesh can be disappeared by the following code.
```suggestion
The default controller mesh can be hidden with the following code.
```

2019-07-04 18:40 UTC, deltakosh requested changes
One English fix

2019-07-04 18:46 UTC, flushpot1125 commented on content/How_To/camera/WebVR_Camera.md
> +The default controller mesh can be disappeared by the following code.
Thanks for fixing the grammatical mistake.

2019-07-04 18:48 UTC, flushpot1125 reviewed
Thanks for fixing the grammatical mistakes.

2019-07-04 19:23 UTC, deltakosh commented on content/How_To/camera/WebVR_Camera.md
> +The default controller mesh can be disappeared by the following code.
You did not apply my suggestion:)

2019-07-04 22:33 UTC, flushpot1125 commented
Sorry for your inconvenience. I tried it according to the article.
https://help.github.com/en/articles/incorporating-feedback-in-your-pull-request#applying-suggested-changes

2019-07-04 23:33 UTC, merged

2019-07-05 02:10 UTC, flushpot1125 commented
I appreciate it! :)