Documentation for exporting 3DS Max model with animation to babylon or gltf
BabylonJS/OldDocumentationSite pull request #816
Opened 2018-02-09 12:23 UTC by ravip

Documentation for exporting 3DS Max model with animation to babylon or gltf

2018-02-09 14:54 UTC, deltakosh requested changes
Can you please save imaged in punlic/html/imgs (or something like that:) I'm on my phone)?
You then then just use /imgs/xxx to reference them

2018-02-13 10:43 UTC, RaananW commented on content/resources/Exporter/3DSMax_babylon_or_gltf_with_animations
> +Steps to export any 3D model with animation to .babylon / .gltf format
Since this is a new page it requires a title. This line fits nicely. Can also be a bit shorter for the title with a bit more details right after.

2018-02-13 11:19 UTC, ravip commented
@RaananW 
Directory "content/resources/Exporter" contains .md files. I have used naming conventions similar to existing files. Would you be kind enough to check the existing file names @ "content/resources/Exporter" and suggest changes appropriately.

2018-02-13 12:06 UTC, RaananW commented
Hi @ravip , my comment is not about the naming but about the formatting. Notice how every document starts with "#Title Of This Document" (Just as an example - https://github.com/BabylonJS/Documentation/blob/master/content/resources/Exporter/3DSMax.md )
This allows our html-generator to create the page correctly.

2018-02-13 12:16 UTC, ravip commented
@RaananW Thanks for updated info. Changes done accordingly.

2018-02-13 16:21 UTC, deltakosh commented
I would recommend updating this one actually: https://github.com/BabylonJS/Documentation/blob/master/content/resources/Exporter/3DSMax_to_glTF.md

2018-02-14 17:03 UTC, deltakosh commented
up?

2018-02-15 06:23 UTC, ravip commented
@deltakosh I would be happy if you would like me to modify existing file https://github.com/BabylonJS/Documentation/blob/master/content/resources/Exporter/3DSMax_to_glTF.md

Please confirm.

2018-02-15 14:28 UTC, deltakosh commented
I confirm:)

2018-02-16 14:16 UTC, deltakosh requested changes

2018-02-16 14:16 UTC, deltakosh commented on content/resources/Exporter/3DSMax_to_glTF.md
> +10.Check the exported model with BabylonJS sandbox http://sandbox.babylonjs.com/, animations and model will get exported properly.
This is a duplicate of the following chapter

2018-02-16 14:16 UTC, deltakosh commented on content/resources/Exporter/3DSMax_to_glTF.md
> +1.Install 3ds Max 2017
No need to mention the installation as it has already been covered before

2018-02-16 14:53 UTC, deltakosh requested changes

2018-02-16 14:53 UTC, deltakosh commented on content/resources/Exporter/3DSMax_to_glTF.md
> +1. Add Babylon plugin to 3ds MAX 2017 https://doc.babylonjs.com/resources/3dsmax
Sorry:( but even this one is redundant

2018-02-16 14:53 UTC, deltakosh commented on content/resources/Exporter/3DSMax_to_glTF.md
> +1. Add Babylon plugin to 3ds MAX 2017 https://doc.babylonjs.com/resources/3dsmax
So sorry 
Can you also remove this one as it is redundant

2018-02-16 15:07 UTC, deltakosh approved these changes
Wonderful! Thanks a lot

2018-02-16 15:08 UTC, merged