Update materials  and update vertexData
BabylonJS/OldDocumentationSite pull request #834
Opened 2018-02-28 10:12 UTC by BabylonJSGuide

Looking at a couple of 'solved' topics in the forum have added the solutions into the documentation.

Added information on pointsCloud and setVetexData

2018-02-28 10:28 UTC, RaananW approved these changes
thanks a lot!

2018-02-28 10:30 UTC, RaananW requested changes

2018-02-28 10:30 UTC, RaananW commented on content/How_To/mesh/Updating_Vertices.md
>  [Playground Example Scaling Positions](http://www.babylonjs-playground.com/#VE6GP#4)
Please make this bullet points or at least separate the lines, otherwise it is just a long list

2018-02-28 10:30 UTC, RaananW commented on content/features/component/Materials.md
> +[Playground Example - Points Cloud](https://www.babylonjs-playground.com/#PGY5FG)
Same here (bullet points)

2018-02-28 13:50 UTC, BabylonJSGuide commented
Sorry @RaananW do not see the issue, when built it looks like this  []([https://i.imgur.com/2L1ef91.png](https://i.imgur.com/2L1ef91.png)) and the code seems to me to break it up from being just a list. If you could clarify what needs bullet points and why I will see what I can do.

2018-02-28 13:52 UTC, BabylonJSGuide commented
Also now added new page in samples

2018-02-28 14:34 UTC, RaananW commented
What I mean is the playground links:
![image](https://user-images.githubusercontent.com/1381702/36793120-d2f7babe-1c9c-11e8-9199-a4d15353ca51.png)

you could add a * before each of them, and it will look like this:

* link 1
* link 2

2018-02-28 14:47 UTC, BabylonJSGuide commented
In the build I get [https://i.imgur.com/Fzy7EYm.png](https://i.imgur.com/Fzy7EYm.png) I think the process of adding the eye and playground frame automatically puts them on separate lines. I agree that looking at a preview (as I do in Visual Studio Code) does make them look like they are in a list but they do work out OK on build. Have not yet worked out why the build sometimes adds an extra line though.

2018-02-28 14:51 UTC, RaananW commented
Would be great to stay conform with markdown, just in case we are changing the markdown engine.
You removed the lines between the playgrounds. If there is aline between them (an extra break line) they will be separated. That is, if you want to avoid bullet points.

2018-02-28 15:16 UTC, BabylonJSGuide commented
If you check out from line 137 in scripts/compile-html/compile-html-statics.js the code replaces anything to do with a playground link and it is this rather than any markdown engine that determines that these are on a new line. However for consistency I have now replaced any entry in the documentation that starts [Playground  with * [Playground and so all playground examples of this form will be indented as bullet points. Will update pull request in a moment.

2018-02-28 18:52 UTC, RaananW commented
So no need for bullet points, just a separate line between them. If I udnerstand correctly. 

I just don't think single-line playground should be with bullet points :smile:

But if this is the solution, I am fine with it.

2018-02-28 19:13 UTC, BabylonJSGuide commented
If you put a single line between them you end up with at least two lines
between them after the build. Putting in bullet points does seem to solve
the occasional extra line problem. Putting a bullet point for one line does
not look too bad for the playground examples it looks more like a form of
emphasis. Will not be doing anymore until tomorrow so let me know if you
want it left with bullet points for all or for none and I will sort it out
tomorrow.

On 28 Feb 2018 6:54 pm, "Raanan Weber" <notifications@github.com> wrote:

> So no need for bullet points, just a separate line between them. If I
> udnerstand correctly.
>
> I just don't think single-line playground should be with bullet points 😄
>
> But if this is the solution, I am fine with it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BabylonJS/Documentation/pull/834#issuecomment-369343204>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASwoao1GklY85Ei9ES3CJO4Qfz3cElJhks5tZaBzgaJpZM4SWZZp>
> .
>

2018-02-28 19:14 UTC, RaananW commented
So! Instead of trying to solve a non-existing problem, I trust you to do the right thing. Whenever you tell me that it is fine, I will merge it :)
Sorry for the hassle.

2018-03-01 09:22 UTC, BabylonJSGuide commented
Had another look at local build and looks OK with each playground example set with a bullet point whether an individual or a list. Will keep things as they are from latest push. No hassle better to communicate and get an agreement. Please merge.

2018-03-01 09:23 UTC, RaananW approved these changes

2018-03-01 09:23 UTC, merged

2018-03-01 09:24 UTC, BabylonJSGuide commented
Thank you